[Variables]
@include=#SKINSPATH#MySkins\TNotebook Skin\MainVaribles.inc



;;;;;;;;;;;;;;;;;;;;;;;RAM
[RamPercent]
StringAlign=Right
StringStyle=Bold
FontColor=#MColor3#
FontSize=#FontHeight11#
FontFace=#FontName#
AntiAlias=1
Percentual=1

[RAMText]
StringAlign=Left
StringStyle=Bold
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#

[RAMStat]
StringAlign=Right
StringStyle=Bold
FontColor=#MColor2#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[RAMStat2]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight8#
FontFace=#FontName#
AntiAlias=1

[RAMStat3]
StringAlign=Right
FontColor=#MColor2#
FontSize=#FontHeight8#
FontFace=#FontName#
AntiAlias=1

[RAMGraph]
StringStyle=Bold
Flip=0
BarColor=#MColor3#
BarOrientation=vertical
;;;;;;;;;;;;;;;;;;;;;;;/RAM

;;;;;;;;;;;;;;;;;;;;;;;CPU
[CPUPercent]
StringAlign=Right
StringStyle=Bold
FontColor=#MColor3#
FontFace=#FontName#
FontSize=11
AntiAlias=1

[CPUPercent2]
StringAlign=Right
StringStyle=Bold
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[CPUPercent3]
StringAlign=Right
StringStyle=Bold
FontColor=#MColor2#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[CPUText]
StringAlign=Left
StringStyle=Bold
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[CPUText2]
StringAlign=Left
StringStyle=Bold
FontColor=#MColor6#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[CPUGraph]
StringStyle=Bold
PrimaryColor=#MColor3#
Flip=0
;;;;;;;;;;;;;;;;;;;;;;;/CPU

;;;;;;;;;;;;;;;;;;;;;;;NetDown
[NetInAllMText]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#

[NetInAllText]
StringAlign=Left
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#

[NetTrafficDLText]
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[NetTrafficDl]
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1
;;;;;;;;;;;;;;;;;;;;;;;/NetDown

;;;;;;;;;;;;;;;;;;;;;;;NetUp
[NetOutAllMText]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#

[NetOutAllText]
StringAlign=Left
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#

[NetTrafficUpText]
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[NetTrafficUp]
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1
;;;;;;;;;;;;;;;;;;;;;;;/NetUp

;;;;;;;;;;;;;;;;;;;;;;;TrashBin
[SChangeAction1]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SChangeAction2]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMain]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMeterSize]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMeterCount]
StringAlign=Center
FontColor=#MColor4#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1
;;;;;;;;;;;;;;;;;;;;;;;/TrashBin

;;;;;;;;;;;;;;;;;;;;;;;Clock
[style]
FontFace=a_LCDNova
FontSize=22
StringStyle=BOLD
AntiAlias=1
StringAlign=Center
FontColor=#ClockColor#,150

[style2]
FontFace=a_LCDNova
FontSize=10
StringStyle=BOLD
AntiAlias=1
StringAlign=Left
FontColor=#ClockColor#,50
;;;;;;;;;;;;;;;;;;;;;;;/Clock

;;;;;;;;;;;;;;;;;;;;;;;Wi-FI
[WNetAllText]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[WNetAllRezText]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1
;;;;;;;;;;;;;;;;;;;;;;;/Wi-FI

;;;;;;;;;;;;;;;;;;;;;;;NetInfo
[SMText_UpTime]
StringAlign=Left
Fontsize=#FontHeight9#
Fontface=#FontName#
FontColor=#MColor1#
AntiAlias=1

[SText_UpTime]
StringAlign=Right
Fontsize=#FontHeight9#
Fontface=#FontName#
FontColor=#MColor3#
AntiAlias=1

[SMText_ExternalIP]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SText_ExternalIP]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMText_LANIP]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SText_LANIP]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMText_DNSIP]
StringAlign=Left
FontColor=#MColor1#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SText_DNSIP]
StringAlign=Right
FontColor=#MColor3#
FontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SText_MeterPing]
StringAlign=Left
fontColor=#MColor1#
fontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMeterPing]
StringAlign=Right
fontSize=#FontHeight9#

[SText_MeterPingServer]
StringAlign=Left
fontColor=#MColor1#
fontSize=#FontHeight9#
FontFace=#FontName#
AntiAlias=1

[SMeterPingServer]
StringAlign=Right
fontSize=#FontHeight9#
;;;;;;;;;;;;;;;;;;;;;;;/NetInfo